### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by clemensruppelt** [clemensruppelt/bassum-liest-bibel#1]
To keep track, here's a todo list
- [ ] add footmarks (* so lange Vorrat reicht ** Widerruf kann jederzeit erfolgen)
- [ ] replace picture with a licensed highres one
- [ ] add additional text from pdf template
- [ ] add ref to www.gott-in-bassum.de
